name: Build and deploy Node.js app to Azure Web App - chatlog-annotator-exp

on:
  push:
    branches:
      - nodjango2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        env:
          DEFAULT_COSMOSDB_ENDPOINT: ${{ secrets.DEFAULT_COSMOSDB_ENDPOINT }}
          DEFAULT_COSMOSDB_DATABASE: ${{ secrets.DEFAULT_COSMOSDB_DATABASE }}
          DEFAULT_COSMOSDB_CONTAINER: ${{ secrets.DEFAULT_COSMOSDB_CONTAINER }}
          DEFAULT_COSMOSDB_USER_COLLECTION: ${{ secrets.DEFAULT_COSMOSDB_USER_COLLECTION }}
          DEFAULT_COSMOSDB_DATABASE_COLLECTION: ${{ secrets.DEFAULT_COSMOSDB_DATABASE_COLLECTION }}
          DEFAULT_DATABASE_NAME: ${{ secrets.DEFAULT_DATABASE_NAME }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chatlog-annotator-exp"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A0843A38014646E88DB185863F0E64D3 }}
          env: |
            COSMOSDB_ENDPOINT=${{ secrets.COSMOSDB_ENDPOINT }}
            COSMOSDB_DATABASE=${{ secrets.COSMOSDB_DATABASE }}
            COSMOSDB_CONTAINER=${{ secrets.COSMOSDB_CONTAINER }}
            COSMOSDB_USER_COLLECTION=${{ secrets.COSMOSDB_USER_COLLECTION }}
