name: Build and deploy Node.js app to Azure Web App - chatlog-annotator-exp

on:
  push:
    branches:
      - nodjango2
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const artifact of res.data.artifacts) {
              try {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact ${artifact.id}`);
              } catch (error) {
                console.error(`Failed to delete artifact ${artifact.id}: ${error}`);
              }
            }

  build:
    needs: cleanup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies and build
        env:
          DEFAULT_COSMOSDB_ENDPOINT: ${{ secrets.DEFAULT_COSMOSDB_ENDPOINT }}
          DEFAULT_COSMOSDB_DATABASE: ${{ secrets.DEFAULT_COSMOSDB_DATABASE }}
          DEFAULT_COSMOSDB_CONTAINER: ${{ secrets.DEFAULT_COSMOSDB_CONTAINER }}
          DEFAULT_COSMOSDB_USER_COLLECTION: ${{ secrets.DEFAULT_COSMOSDB_USER_COLLECTION }}
          DEFAULT_COSMOSDB_DATABASE_COLLECTION: ${{ secrets.DEFAULT_COSMOSDB_DATABASE_COLLECTION }}
          DEFAULT_DATABASE_NAME: ${{ secrets.DEFAULT_DATABASE_NAME }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "node_modules/*" "*.git*" "*test*" "*coverage*"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./release
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chatlog-annotator-exp"
          slot-name: "Production"
          package: ./release
