import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";

export const metadata: Metadata = {
  title: "Chat Log Annotators",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights like 400 (regular) or 700 (bold)
  variable: "--font-sans-serif", // Optional: Define a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang = "en" suppressHydrationWarning>
      <body className = "bg-black text-white"
      style={{ fontFamily: `${roboto.variable} monospace` }}>
        {children}
      </body>
    </html>
  );
}
